project:
  type: website
  output-dir: docs

website:
  title: "Meg Branine"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - href: CV.qmd
        text: My CV
      - href: resources.qmd
        text: Resources
      - href: projects.qmd
        text: Projects

format:
  html:
    theme:
      - united
      - brand
    css: styles.css
    toc: true



