project:
  type: website
  output-dir: docs

website:
  title: "octopuses_are_amazing"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - href: CV.qmd
        text: My CV
      

format:
  html:
    theme:
      - united
      - brand
    css: styles.css
    toc: true



