---
title: "Curriculum Vitae"
---

<center>

## **Margaret E. Branine**

</center>

<center>*Updated February 2026*</center>

<br> <br>

#### **Education**

####### **Cornell University**

-   August 2020- Present

-   PhD Candidate in the Department of Microbiology

-   Advisor: Dr. Teresa Pawlowska

####### **Montana State University - Bozeman**

-   August 2015- May 2020

-   B.S. in Microbiology

-   Minor in Astrobiology

-   GPA: 3.85/4.0

#### **Publications**

-   **Branine, M.** and Pawlowska, T. (2026). More than the sum of its parts: the significance of reproductive addiction in the ecology and evolution of fungal-bacterial symbioses. *Microbiology and Molecular Biology Reviews* (submitted).

-   Bazzicalupo, A. L., Erlandson, S., **Branine, M.**, Ratz, M., Ruffing, L., Nguyen, N. H., & Branco, S. (2022). Fungal Community Shift Along Steep Environmental Gradients from Geothermal Soils in Yellowstone National Park. *Microbial Ecology*, 84(1), 33-43. <https://doi.org/10.1007/s00248-021-01848-y>

-   **Branine, M.**, Bazzicalupo, A., & Branco, S. (2019). Biology and applications of endophytic insect-pathogenic fungi. *PLoS Pathogens*, 15(7), 1–7. <https://doi.org/10.1371/journal.ppat.1007831>

#### **First Author Presentations**

-   **Branine, M.**, Scales, E., Mondo, S., and Pawlowska, T. (March 3, 2025) *Coupling genome-wide positive selection analysis with transcriptomics to infer molecular bases of the* Rhizopus microsporus – Mycetohabitans *symbiosis*. \[Poster session\]. European Conference on Fungal Genetics. Dublin, Ireland.

-   **Branine, M.**, Scales, E., Mondo, S., and Pawlowska, T. (March 2, 2025) *Coupling genome-wide positive selection analysis with transcriptomics to infer molecular bases of the* Rhizopus microsporus – Mycetohabitans *symbiosis*. \[Oral presentation\]. European Conference on Fungal Genetics (3rd Symposium on the Basal Fungal Kingdom). Dublin, Ireland.

-   **Branine, M.**, Scales, E., and Pawlowska T. (October 3, 2024) *Inferring molecular bases of the* Rhizopus microsporus - Mycetohabitans *symbiosis by genome-wide positive selection analysis*. \[Oral presentation\]. JGI Annual User Meeting (Multi-Omics of Microbial Eukaryotes Workshop), Walnut Creek, CA.

-   **Branine, M.**, Scales, E., and Pawlowska T. (October 1, 2024) *Inferring molecular bases of the* Rhizopus microsporus - Mycetohabitans *symbiosis by genome-wide positive selection analysis*. \[Poster session\]. JGI Annual User Meeting, Walnut Creek, CA.

-   **Branine, M.** and Pawlowska, T. (March 14, 2024). *Inferring molecular bases of the* Rhizopus microsporus – Mycetohabitans *symbiosis by genome-wide positive selection analysis* \[Poster session\]. Fungal Genetics Conference, Asilomar, CA.

-   **Branine, M.** and Teresa Pawlowska. (March 12, 2024). *Inferring molecular bases of the* Rhizopus microsporus – Mycetohabitans *symbiosis by genome-wide positive selection analysis* \[Oral presentation\]. Fungal Genetics Conference (2nd Symposium on the Basal Fungal Kingdom), Asilomar, CA.

-   **Branine, M.** (February, 2023). *Investigating the role of adenylyl cyclases in innate immune responses of* Rhizopus microsporus \[Seminar\]. Department of Microbiology Graduate Seminar Series, Cornell University.

-   **Branine, M.**, Real-Ramirez, I., Hoseon Choi, S., Mondo, S., and Pawlowska, T. (October 11, 2022). *Probing the role of N6-methyladenine DNA modifications in the* Rhizopus microsporus-Mycetohabitans *symbiosis* \[Poster session\]. Department of Microbiology Annual Symposium, Cornell University.

-   **Branine, M.** (May, 2022). *Probing the role of N6-methyladenine DNA modifications in the* Rhizopus microsporus-Mycetohabitans *symbiosis* \[Seminar\]. Department of Microbiology Graduate Seminar Series, Cornell University.

-   **Branine, M.**, Real-Ramirez, I., Hoseon Choi, S., Mondo, S., and Pawlowska, T. (March 17, 2022). *Probing the role of N6-methyladenine DNA modifications in the* Rhizopus microsporus-Mycetohabitans *symbiosis* \[Oral Presentation\]. Fungal Genetics Conference, Asilomar, CA.

-   **Branine, M.**, Real-Ramirez, I., Hoseon Choi, S., Mondo, S., and Pawlowska, T. (March 16, 2022). *Probing the role of N6-methyladenine DNA modifications in the* Rhizopus microsporus-Mycetohabitans *symbiosis* \[Poster session\]. Fungal Genetics Conference, Asilomar, CA, United States.

-   **Branine, M.**, Hager, M., Erlandson, S., & Branco, S. (March, 2020). *Investigating ecological trade-offs in endophytic insect pathogenic fungi* \[Poster session\]. National Conference on Undergraduate Research, Bozeman, MT, United States. (Accepted - conference canceled due to COVID-19)

-   **Branine, M.**, Hager, M., Erlandson, S., Branco, S. (August, 2019). *Investigating ecological trade-offs in endophytic insect pathogenic fungi* \[Poster Session\]. Mycological Society of America Meeting, Minneapolis, MN, United States.

#### **Other Presentations**

-   Reynolds, N., Amses, K., Uehling, J., Adeleke, R., Sternberg, M., **Branine, M.**, Pawlowska, T. (July 1, 2025). *Structure of Mucoromycota fungal communities and their associated endosymbiotic bacteria across two different biomes in the U.S. and Israel.* \[Oral presentation\]. The Mycological Society of America Annual Meeting, Madison, WI, USA.

-   Reynolds, N., Amses, K., Uehling, J., Adeleke, R., **Branine, M.**, Pawlowska, T. (March 15, 2024). *Dispersal and biotic filtering structure Mucoromycota fungal communities and their associated bacteria across two different biomes* \[Poster session\]. Fungal Genetics Conference, Asilomar, CA, USA.

-   Reynolds, N., Amses, K., Uehling, J., Adeleke, R., **Branine, M.**, Pawlowska, T. (March 14, 2024). *Dispersal and biotic filtering structure Mucoromycota fungal communities and their associated bacteria across two different biomes* \[Oral presentation\]. Fungal Genetics Conference, Asilomar, CA, USA.

-   Reynolds, N., Amses, K., Uehling, J., Adeleke, R., **Branine, M.**, Pawlowska, T. (March 12, 2024). *Dispersal and biotic filtering structure Mucoromycota fungal communities and their associated bacteria across two different biomes* \[Oral presentation\]. Fungal Genetics Conference (2nd Symposium on the Basal Fungal Kingdom), Asilomar, CA, USA.

-   Reynolds, N., Amses, K., Uehling, J., Adeleke, R., **Branine, M.**, Pawlowska, T. (August 1, 2023). *What network analyses can do for you: methods overview and a case study in Mucoromycota fungal-bacterial community associations from rhizosphere soils*. \[Oral presentation\]. The Mycological Society of America Annual Meeting, Flagstaff, AZ, USA.

#### **Honors and Awards**

-   2024: USDA Predoctoral Fellowship: *Epigenetic modifications of fungal DNA as a target for biocontrol of early-diverging fungal pathogens* (proposal number 2023-11542) (\$180,000)

-   2024: CALS Outstanding Teaching Assistant Award (\$100 cash prize)

-   2022: Best Poster - Cornell Department of Microbiology Annual Symposium (\$250 cash prize)

-   2021: Honorable Mention - NSF Graduate Research Fellowship Program

-   2020-2021: Cornell University Graduate School Fellowship (\$37,381)

-   2019: Montana State University College of Agriculture Student Scholar Travel Award (\$500)

-   2019: Irving L. Weissman Undergraduate Biomedical Research Support Fund (\$1,000)

-   2019: Mycological Society of America Mentor Student Travel Award (\$750)

-   2018: Montana State University Undergraduate Scholars Program Research Grant (\$900)

#### **Teaching Experience**

-   Graduate Teaching Assistant for BioG 1445 - Comparative Anatomy and Physiology (Cornell University)
    -   Fall 2021, Fall 2022, Spring 2023, Fall 2023, Spring 2024.
    -   Write and administer individual oral exams, lead a lab section, grade lab reports, tutor students (one-on-one and small group settings)
-   Graduate Teaching Assistant for NSF-funded Research Experience for Undergraduates *Microbial Friends and Foes* (Cornell University)
    -   Summer 2022
    -   Review and provide feedback on student summer research proposals and presentations, organize and facilitate professional development and networking opportunities

#### **Courses and Training**

-   *Analysis of DNA Methylation (Instats)*. Virtual. October 27-29, 2025.

-   *Genome Assembly and Annotation (Physalia)*. Virtual. March 17-21, 2025.

-   *Integrated Microbial Genomes Workshop (JGI)*. Walnut Creek, CA. October 5, 2024.

-   *Adaptation Genomics (Physalia)*. Virtual. June 24-28, 2024.

-   *Advanced Course in Phylogenomics and Population Genomics: Inference and Applications*. University of Barcelona, Barcelona, Spain. July 4-14, 2023.

-   *Workshop on Molecular Evolution*. Marine Biological Laboratory, Woods Hole, MA. May 26 - June 5, 2023.

#### **Service and Outreach**

-   2025- present: *Vaccination Conversations with Scientists (VACS):* Science Handout Team (research and create evidence-based materials for public education on vaccine science)
-   2024-2025: *Write a Researcher* : Treasurer
-   2023-24: *Write a Researcher:* Communications Officer
-   2022-2023: *Write a Researcher* (Correspondence with high school students about research and STEM)
-   2021: *Expanding Your Horizons* at Cornell University. Group Leader
-   2019: STEM Night at Heck-Quaw Elementary School Belgrade, MT. Presenter (with Branco Lab)
-   2019: Crossroads of Discovery (Celebration of Undergraduate Research at Montana State University). Presenter
-   2019: *Expanding Your Horizons* at Montana State University. Group Leader
-   2018-2019, 2015-2016: Montana Space Grant Consortium Space Public Outreach Team (SPOT) Presenter
-   2017: Freshman Research Symposium Montana State University. Presenter (with Branco Lab)
-   2017: Volunteer at Montana Science Olympiad
-   2016: Expanding Your Horizons at Montana State University. Presenter with SPOT: *Pluto and Beyond*
-   2016: Organizer: Native Youth Preview Day at Montana State University
-   2015: Volunteer at Montana Science Olympiad
